# Pull from the ubuntu:14.04 image
FROM ubuntu:14.04

MAINTAINER Vu Tran <vu@vu-tran.com>

RUN apt-get update && apt-get -y install \
    software-properties-common \
    python-software-properties \
    debian-archive-keyring \
    wget \
    curl \
    vim \
    aptitude \
    dialog \
    net-tools \
    mcrypt \
    build-essential \
    tcl8.5 \
    git

RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com C300EE8C

RUN add-apt-repository ppa:nginx/stable

RUN apt-get update && apt-get -y install \
    nginx \
    php5-fpm \
    php5-cli \
    php5-mysql \
    php5-curl \
    php5-mcrypt \
    php5-gd \
    php5-redis

RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf

RUN cp /etc/php5/fpm/php.ini /etc/php5/fpm/php.ini.original.bak
RUN mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.original

# Configure PHP settings
RUN perl -pi -e 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php5/fpm/php.ini
RUN perl -pi -e 's/allow_url_fopen = Off/allow_url_fopen = On/g' /etc/php5/fpm/php.ini
RUN perl -pi -e 's/expose_php = On/expose_php = Off/g' /etc/php5/fpm/php.ini

# Copy default site conf
COPY default.conf /etc/nginx/sites-available/default

# Copy the index.php file
COPY index.php /var/www/html/index.php

VOLUME ["/etc/nginx/certs", "/etc/nginx/conf.d", "/var/www/html"]

CMD service php5-fpm start && nginx

WORKDIR /var/www/html

# Expose port 80
EXPOSE 80
EXPOSE 443
